# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Distribute debug build to Firebase App Distribution"
  lane :distribute_debug do
      firebase_app_distribution(
          app: ENV["FIREBASE_APP_ID_ANDROID"],
          apk_path: "../build/app/outputs/flutter-apk/app-dev-debug.apk",
          firebase_cli_token: ENV["FIREBASE_TOKEN"]
      )
  end

  desc "Distribute release build to Google Play"
  lane :distribute_release do
    upload_to_play_store(
      aab: "../build/app/outputs/bundle/prodRelease/app-prod-release.aab",
      json_key_data: ENV["GOOGLE_PLAY_JSON_KEY"]
    )
  end
end
